# GIT სრული პროცესი (ერთად)

# 1. დაყენება

sudo apt update
sudo apt install git -y

# 2. კონფიგურაცია

git config --global user.name "dato-sukhiashvili"
git config --global user.email "[your@email.com](mailto:your@email.com)"

# 3. პროექტი

mkdir my-project
cd my-project
git init

# 4. ფაილი

echo "# Network Notes" > network-notes.txt

# 5. commit

git add .
git commit -m "first commit"

# 6. GitHub დაკავშირება

git remote add origin https://github.com/dato-sukhiashvili/my-project.git

# 7. ატვირთვა

git push -u origin main

# 8. როცა მოგთხოვს

# Username: dato-sukhiashvili

# Password: TOKEN
